### ISSUE TITLE
broken links for the slides on opf website

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/operate-first-data-science-community#76]
![image](https://user-images.githubusercontent.com/26301643/161625432-c4fb503d-f42d-444d-b2f3-c1f500eb5c57.png)

**Comment by oindrillac** [comment]
I think this is happening because the site is trying to load the pdfs within the site which it doesn't support. Currently I think only md and ipynb are supported. 

A workaround could be to use full urls instead of relative urls in the agenda doc. Example instead of `[Slides](content/opfmeetup8.pdf)` using `[Slides](https://github.com/aicoe-aiops/operate-first-data-science-community/blob/main/docs/content/opfmeetup8.pdf)` so we're taken to GitHub instead.

**Comment by aakankshaduggal** [comment]
Thank you @oindrillac, I will do this instead.
