### ISSUE TITLE
how we interface with the operate first community

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/operate-first-data-science-community#82]
![image](https://user-images.githubusercontent.com/32435206/163017799-05bcdc2f-e49b-46a2-a02f-15ce13cbf1b8.png)

The Operate first website WG has [plans](https://miro.com/app/board/uXjVOBO_7kw=/?userEmail=kwade@redhat.com&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-board&utm_content=go-to-board) to reorganize the [operate-first.cloud](https://www.operate-first.cloud/) website. We need to think about where this OSG - Sub Project fits in and how we plan to continue our activities moving forward.

It was proposed that we continue to function as a Special Interest Group in operate first which hosts these meetups.

**Questions -** 
- Should this repo eventually go under the operate-first org?
- Should we function as a data science SIG in operate first moving forward?
- Where does our landing page go after the reorganization? Is it under About the Community/SIG?

**Comment by MichaelClifford** [comment]
**Here are a couple of answers to your questions from my perspective:**

> Should this repo eventually go under the operate-first org?

Sure! It probably makes sense for all of the OPF  DS community work to be moved over there eventually and be dictated under the OPF governance instead of the current OSG governance now things are up and running. We just need to determine a transition plan.  

> Should we function as a data science SIG in operate first moving forward?

If the Operate First Community would like to have a DS SIG we can help to get is started and model it off our OSG DS SIG. However, I'm not sure 2 DS SIGS that contain the same people under 2 different orgs is the best idea long term. 

>  Where does our landing page go after the reorganization? Is it under About the Community/SIG?

Wherever it makes the most sense given the new website design. 


@schwesig This sounds like an issue that would be relevant to `Build a community around the Operate First Community Cloud` let us know if you have any thoughts on how to proceed here :smiley:
